// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-zRcz3jo_IUO0u6eQC3b0j6mIMi5OdH8',
    appId: '1:534706200334:web:e083da7d7a397634b3c15f',
    messagingSenderId: '534706200334',
    projectId: 'shiproute-bf703',
    authDomain: 'shiproute-bf703.firebaseapp.com',
    storageBucket: 'shiproute-bf703.firebasestorage.app',
    measurementId: 'G-5FT8HNKGVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3m65sIDxTptSoZxgsm4laf-LQ4CjPBYM',
    appId: '1:534706200334:android:1613358da907c192b3c15f',
    messagingSenderId: '534706200334',
    projectId: 'shiproute-bf703',
    storageBucket: 'shiproute-bf703.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjHEtLRBY0syrUd_bLhRONHdbNr6ernlA',
    appId: '1:534706200334:ios:783d30a3b3d6045db3c15f',
    messagingSenderId: '534706200334',
    projectId: 'shiproute-bf703',
    storageBucket: 'shiproute-bf703.firebasestorage.app',
    iosBundleId: 'com.example.goodsDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjHEtLRBY0syrUd_bLhRONHdbNr6ernlA',
    appId: '1:534706200334:ios:783d30a3b3d6045db3c15f',
    messagingSenderId: '534706200334',
    projectId: 'shiproute-bf703',
    storageBucket: 'shiproute-bf703.firebasestorage.app',
    iosBundleId: 'com.example.goodsDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-zRcz3jo_IUO0u6eQC3b0j6mIMi5OdH8',
    appId: '1:534706200334:web:93a544644424375cb3c15f',
    messagingSenderId: '534706200334',
    projectId: 'shiproute-bf703',
    authDomain: 'shiproute-bf703.firebaseapp.com',
    storageBucket: 'shiproute-bf703.firebasestorage.app',
    measurementId: 'G-21Y6BSYBX8',
  );
}
